// this file contains the titles and contents for each unlockable note
// this file is generated by the pre-processor from .txt files in the assets/notes directory
function loadAllNoteResources() {
  NotePool.loadNote("Title Goes Here", "This is the body. These are sentences.\nThis is a sentence after a line break.\n\nThis is a sentence after 2 line breaks. Cool, Right?");
  NotePool.loadNote("I am a title", "I am a body.\nI am a body paragraph too!\nI am a body paragraph three!");
}
